#!/usr/bin/env bash

# System dependent
colorflag="-G"

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../../"
alias .....="cd ../../../../"

# Shortcuts
alias down="cd ~/Downloads"
alias docs="cd ~/Documents"
alias p="cd ~/projects"
alias fun="cd ~/projects/fun"
alias os="cd ~/projects/opensource"
alias dot="cd ~/dotfiles"
alias todo="vim ~/org/todo.org"

# Zet
alias zc="cd $HOME/zet"

# Git
alias g="git"
alias gr="git rebase -i HEAD~2"
alias grm="git branch --merged | egrep -v \"(^\*|main)\" | xargs git branch -d"

# Kubectl
alias k="kubectl"

# List in long format
alias l="ls ${colorflag}"
alias ll="ls -lF ${colorflag}"

# List all files
alias la="ls -A ${colorflag}"

# List all directories
alias lsd="l | grep --color=never '^d'"

# Use color output for ls
alias ls="command ls ${colorflag}"

# Get ip4 address
alias ip4="hostname -I | awk '{print \$1}'"

# Colorize grep output
alias grep="grep --color=auto"

# Alias deprecated grep commands
alias fgrep="grep -F"
alias egrep="grep -E"

# Allow aliases to be sudo'ed
alias sudo='sudo '

# Functions
alias urlencode='python3 -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Elfsquad
eqdir=/home/stan/elfsquad/devstack
if [ -d $eqdir ]; then
  source $eqdir/.aliases $eqdir/..
fi

# Miscenallenous
alias bashrc="nvim ~/dotfiles/.bashrc"
alias c="clear"

for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "${method}"="lwp-request -m '${method}'"
done

alias elfsquad="node /home/stan/elfsquad/elfsquad-cli/dist/index.js"

eval "$(github-copilot-cli alias -- "$0")"

