#!/usr/bin/env bash

export PATH=$HOME/.dotnet:$PATH
export PATH=$HOME/.dotnet/tools:$PATH
export PATH=$HOME/dotfiles/scripts:$PATH
export PATH=$HOME/.krew/bin:$PATH
export PATH=$HOME/.ghcup/bin:$PATH
export PATH=$HOME/go/bin:$PATH
export PATH=/opt/homebrew/bin:$PATH
export PATH=$HOME/Library/Python/3.10/bin:$PATH

export PATH=$HOME/elfsquad/kubernetes/eim:$PATH

