#!/bin/bash

case $1 
in
  "sprint")
    jira sprint list --current -a$(jira me)
    ;;
  "new")
    jira issue list --created week
    ;;
  "unassigned")
    jira sprint list --current -ax
    ;;
  *)
    echo "Usage: $0 {sprint|new}"
    exit 1
    ;;
esac
